ZetaGlest/zetaglest-data

- techs/zetapack/factions/elves/elves.xml
* removed some items that had 0 value
* removed things that weren't necessary
* increased wood, decreased gold
I basically uses Indian.xml as a reference. I haven't play-tested again
The AI yet, but nothing too radical here.
> elves.xml:clean-up

- techs/zetapack/factions/greece/greece.xml
- techs/zetapack/factions/greece/units/trojan_horse/trojan_horse.xml
@Jammyjamjamman suggested the trojan horse could be changed and gave me
some ideas.
what this does:
* starting ep is 1200
* ep is needed to move or produce units
* ep doesn't regenerate
* can produce units very quickly
* sight range of 30
* has no attack skill, but has a max HP of 14000
Updated models for it would make it a lot better.
> greece:trojan horse:proposed major update

- techs/zetapack/factions/specialists/specialists.xml
This fixes the problem I reported on Discord, where the Specialists only
create 4 or 5 units.
> specialists:add wheat field to starting units

- others/megaglest-long-description.txt.in
- others/zetaglest-long-description.txt.in
This is referred to by
https://github.com/ZetaGlest/zetaglest-source/blob/develop/CMakeLists.txt
> zetaglest-long-description:update

- MODS.md
We could add a description but that means it will need to be updated in 2 places: this file and the maintainer's README.md
> MODS.md:add Evolution, mod by @MirceaKitsune

- techs/zetapack/factions/greece/units/onager/onager.xml
- techs/zetapack/factions/romans/units/catapult/catapult.xml
- techs/zetapack/factions/tech/units/catapult/catapult.xml
#98 - increase range of catapults
> Increased the catapult range to 15 for greece, roman and tech units

- techs/zetapack/factions/magic/units/power_golem/power_golem.xml
This reverts the ep requirement back to what @biels had it set to
> power golem:require ep to move

- techs/zetapack/factions/egypt/units/obelisk/obelisk.xml
I think anything that takes so long to build should have armor.
> obelisk.xml:give stone armor, increase value from 0 to 5

- techs/zetapack/factions/magic/units/power_golem/power_golem.xml
In Discord, @KeithSammut suggested reducing the armor to 20 and no one
disagreed xD
> power_golem:reduce armor to 20

- scenarios/benchmark/benchmark.xml
- scenarios/benchmark/benchmark_english.lng
> scenario:benchmark:re-add scenario I mistakenly deleted

- techs/zetapack/factions/magic/units/power_golem/power_golem.xml
- techs/zetapack/factions/magic/upgrades/golem_power/golem_power.xml
Reduced armor even more and increased attack and move EP cost. It should be a situational unit, not a plain overpowered one. Also, the intent is that it should not make sense to morph all your golems into power golems.
> Balance changes for Power Golem

- techs/zetapack/factions/greece/units/atlas/atlas.xml
- techs/zetapack/factions/greece/units/battering_ram/battering_ram.xml
> greece:add splash for larger units

- scenarios/amazones_light/amazones_light.xml
- scenarios/amazones_pro/amazones_pro.xml
> amazones_pro_light:remove cows from Norse

- techs/zetapack/factions/norsemen/units/house/house.xml
- techs/zetapack/factions/norsemen/units/mead_bar/mead_bar.xml
found set to false on 2 buildings
> norse:add uniform select

- techs/zetapack/factions/greece/greece.xml
- techs/zetapack/factions/romans/romans.xml
having mobile units doesn't work well on small maps
> rome and greece:replace defense towers at start

- techs/zetapack/factions/greece/units/advanced_barracks/advanced_barracks.xml
- techs/zetapack/factions/greece/units/engineer/engineer.xml
removed onager from advanced barrack
> greece engineer:can morph into an onager

- techs/zetapack/factions/romans/units/wartime_mechanic/wartime_mechanic.xml
(AI) A lot of engineers were joining attacks and getting killed right
away.
> roman mechanic:remove attack skill

- techs/zetapack/factions/romans/romans.xml
- techs/zetapack/factions/romans/units/blacksmith_shop/blacksmith_shop.xml
- techs/zetapack/factions/romans/units/military_camp/military_camp.xml
- techs/zetapack/factions/romans/units/training_camp/training_camp.xml
@Jammyjamjamman I've been trying to get the romans to build some eagle pillars. Even with the changes shown here, they don't build any.
> [wip] romans:build more eagle pillars

- techs/zetapack/factions/indian/units/archer/archer.xml
- techs/zetapack/factions/indian/units/round_tent/round_tent.xml
- techs/zetapack/factions/indian/units/spearman/spearman.xml
- techs/zetapack/factions/indian/units/stickfighter/stickfighter.xml
- techs/zetapack/factions/indian/units/tent/tent.xml
* stickfighters can morph into spearmen
* spearmen can morph into axe indians
* archers can morph into fire archers
* the small tent can morph into a round_tent
small discounts are received when units are morphed. It's cheaper than
building a new unit, but more expensive than keeping the unit and
building another one.
The time to morph should be greater than the time to produce or build
the target unit (to help with balance)
> indians:add ability to morph some units

- techs/zetapack/factions/british/british.xml
- techs/zetapack/factions/british/units/cannon/cannon.xml
- techs/zetapack/factions/british/units/captain/captain.xml
- techs/zetapack/factions/british/units/cavalry/cavalry.xml
- techs/zetapack/factions/british/units/fort/fort.xml
- techs/zetapack/factions/british/units/grenadier/grenadier.xml
- techs/zetapack/factions/british/units/infantryman/infantryman.xml
- techs/zetapack/factions/british/units/lookout_tower/lookout_tower.xml
- techs/zetapack/factions/british/units/mortar/mortar.xml
- techs/zetapack/factions/british/units/nurse/nurse.xml
- techs/zetapack/factions/british/units/powder_house/powder_house.xml
- techs/zetapack/factions/british/units/puckle_gun/puckle_gun.xml
- techs/zetapack/factions/british/upgrades/medicine/medicine.xml
also moved medicine upgrade from powder house to nurse
> british:fine-tuning/rebalancing

- tilesets/autumn/autumn.xml
Lmao, I updated everything, but forgot to enable the tileset updates with the tileset xml. Now the autumn updates are visible 👍
> Flipped the on switch

- techs/zetapack/factions/indian/units/shaman/shaman.xml
> Changed value of radius shaman from 15 to 5 on line 65 as requested

- techs/zetapack/factions/tech/units/technician/technician.xml
> Add "hold position" skill to technician.

- techs/zetapack/factions/greece/units/chariot/chariot.xml
This reverts commit b7da3a42e5373af738205ecce2ec4f7106d1748d.
I broke the chariot
> Revert "greece/chariot:change cost/remove air attack"
